### ISSUE TITLE
The -d, --destination cmdline option is more like a --prefix

### ISSUE THREAD

**Issue by dnwe** [ferstl/eclipse-builder#4]
Using eclipse-builder and .conf files to generate per-project customized eclipses, I'd initially assumed that `-p linux -n eclipse-project-alpha -d /usr/src/eclipse-project-alpha` would result in eclipse being installed directly into `/usr/src/eclipse-project-alpha`, but instead ended up with  `/usr/src/eclipse-project-alpha/eclipse-project-alpha-linux-gtk-x86_64/eclipse-project-alpha`

It seems like `./eclipse-builder -d, --destination` is intended to act more like the equivalent of `./configure --prefix` rather than a destination per se, I assume as part of the support for building multiple distributions from a single set of scripts.

I wonder if the `-d` option should only be permitted when building for a single platform and would specify an absolute install path. A new `--prefix` or `--basedir` type option could provide the current behaviour, which is useful when building for multiple platforms?

**Comment by ferstl** [comment]
I never used the `--destination` option to install an Eclipse distro directly to the directory where I run it. I used it more to create all distros for different platforms in one directory from where I can pack and publish them.

But you are right, there is one obsolete directory, i.e. the last `eclipse-project-alpha` in your example. In fact, this obsolete directory is bothering me for quite a while but apparently not too much to adjust the script. I'll take a look.

**Comment by ferstl** [comment]
I changed the script so that it doesn't create the last directory anymore. This makes it easier to install your Eclipse distro directly to the directory you like. In your example you could use `--destination /usr/src/ --name eclipse-project-alpha`.

However, there is still the platform suffix in the destination directory. We could add a new option like `--omit-suffix` which is only allowed if one single `--platform` is defined. That is more or less what you suggested and would give you full control over the destination directory's name. What do you think?

**Comment by dnwe** [comment]
@ferstl actually I have no problem with keeping the platform-arch (e.g., linux-gtk-x86_64) suffixes. So I think with the latest changes this issue can be closed.

:+1:
